name: Minimal Push Test

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone & Commit Test
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          REPO=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Pak-iju/doodstr.git

          git clone $REPO repo
          cd repo

          echo "Test at $(date)" >> test.txt

          git add .
          git commit -m "Test push $(date)" || echo "No changes to commit"
          git push
