name: Auto Sync All Files in f/

on:
  push:
    branches:
      - main

jobs:
  sync-all-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone and Sync to Target Repo
        run: |
          REPO1=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Pak-iju/doodstr.git

          git clone $REPO1 repo1

          # Hapus semua file lama di repo target kecuali .git
          find repo1 -mindepth 1 -not -name '.git' -exec rm -rf {} +

          # Salin semua file dari folder f/ ke repo target
          cp -r f/* repo1/

          cd repo1
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto sync all files (with delete support)" || echo "No changes"
          git push
