name: Auto Sync All Files in f/

on:
  push:
    branches:
      - main  # atau ganti sesuai nama branch kamu

jobs:
  sync-all-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone and Copy to Repos
        run: |
          REPO1=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Pak-iju/doodstr.git


          git clone $REPO1 repo1


          cp -r f/* repo1/


          cd repo1
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto sync all files"
          git push
