name: Auto Sync Files in f/

on:
  push:
    branches:
      - main

jobs:
  sync-all-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Clone and Sync to Target Repo
        run: |
          # Ganti dengan URL repo target yang sesuai
          REPO1=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Pak-iju/doodstr.git

          # Clone repo target
          git clone $REPO1 repo1

          # Hapus isi folder f/ di repo target (kecuali .git)
          rm -rf repo1/f/*

          # Salin seluruh file dari folder f/ ke f/ di repo target
          cp -r f/* repo1/f/

          # Commit dan push perubahan
          cd repo1
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync files from f/ to repo target" || echo "No changes"
          git push
